import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../Components/Navbar"
import Footer from "../Components/Footer"
import Header from '../Components/Header'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Ebuy.com - Buy the world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='max-w-[1440px] mx-auto'>
      <Navbar/>
      {/* <div>
        <img src="/home.jpg" className='w-full' alt="" />
      </div> */}

      <Header/>

      <Footer/>
      </div>

      

      
    </div>
  )
}
